### ISSUE TITLE
建议可以把Big Sur与Montery的合并一下

### ISSUE THREAD

**Issue by htmambo** [zabdottler/Lenovo-Yoga-16S-hackintosh#2]
OpenCore支持根据版本号来针对不同系统加载不同的驱动的。

系统|MaxKernel|MinKernel
---|---|---
Big Sur|20.99.99|20.0.0
Montery|21.99.99|21.0.0

不过看到你两个系统下的ACPI不同，不知道Big Sur加载了那两个ACPI有什么问题，我目前是都加载的。

**Comment by zabdottler** [comment]
之所以分开是因为NootedRed在Monterey中需要依赖AMDX5000和X6000的两个kext以SysKC方式注入，而且需要NootedRed定制的OC和Lilu。当然最新版本的NootedRed已经支持Monterey，不再需要那些，后面我会合并一下

**Comment by zabdottler** [comment]
APCI不同是Big Sur的EFI忘记加了，ALS0和PNLF是用于亮度调整的，我现在都是用Monterey所以疏忽了Big Sur的EFI

**Comment by htmambo** [comment]
作者今天更新的可以使用官方的OC了，看后续的更新情况吧。
