### ISSUE TITLE
XHCI0和XHCI1同时使用的修复方法

### ISSUE THREAD

**Issue by Watish** [zabdottler/Lenovo-Yoga-16S-hackintosh#5]
加载GenericUSBXHCI.kext
亲测在小新Air14 ARE可行
文件在该仓库的release包
https://github.com/W2725730722/Lenovo-R7000P-2020-Hackintosh

**Comment by luziyi** [comment]
yoga16s 测试可用 系统版本13.4

**Comment by zabdottler** [comment]
手上目前没有AMD笔记本了，无法测试验证
